export const assets = {
  logo: '/img/4k_logo.png',
  logoFooter: '/img/4k-logo.png',
  hero: {
    background: '/img/banner-bk.jpg',
  },
  banners: {
    supplier: '/assets/banners/supplier-banner.jpg',
    eid: '/assets/banners/eid-banner.jpg',
  },
  countries: {
    bahrain: '/img/countries/bahrain.jpg',
    egypt: '/img/countries/egypt.jpg',
    jordan: '/img/countries/jordan.jpg',
    kuwait: '/img/countries/kuwait.jpg',
    oman: '/img/countries/oman.jpg',
    qatar: '/img/countries/qatar.png',
    saudi: '/img/countries/saudi.jpg',
    uae: '/img/countries/uae.jpg',
  },
  categories: {
    compactSUV: '/img/categories/Compact SUV.png__category.png',
    economy: '/img/categories/Economy[1].png__category.png',
    fullSize: '/img/categories/Full size.png__category.png',
    luxury: '/img/categories/Luxury.png__category.png',
    mini: '/img/categories/MINI.png__category.png',
    minivan: '/img/categories/minivan.png__category.png',
    small: '/img/categories/Small.png__category.png',
    standard: '/img/categories/standard.png__category.png',
    suv: '/img/categories/SUV.png__category.png',
    luxurySuv: '/img/categories/Luxury SUV.png__category.png',
    family: '/img/categories/Family.png__category.png',
  },
  suppliers: {
    alamo: '/img/ALAMO_logo.png',
    avis: '/img/AVIS_logo.png',
    europcar: '/img/Europcar_logo.png',
    hertz: '/img/hertz_logo.png',
    sixt: '/img/SIXT_logo.png',
    highway: '/img/Highway_logodc11c608f2e44e287d25dbed9df19519.png',
    ktc: '/img/KTC_logodc11c608f2e44e287d25dbed9df19519.png',
    mahd: '/img/MAHD_logo4c949f544080391662eeba1eda4ac590.png',
    rama: '/img/RAMA_logodc11c608f2e44e287d25dbed9df19519.png',
    goRental: '/img/GO RENTAL_logof286ceda378c5cc4622aba3ac6afe972.png',
    royalStar: '/img/Royal Star_logo779b164104b2daee4d690f6ae57ca45d.jpg',
    enterprise: '/img/Enterprise_logo.webp',
    budget: '/img/Budget_logo.jpg',
    sovoy: '/img/SOVOY_logo.png',
  },
  vehicles: {
    nissanPatrol: '/img/vehicles/Nissan-Patrol-2024.png_Nissan Patrol Automatic_vehicle_photo.png',
    toyotaCamry: '/img/vehicles/toyota-camry-2025.png_Toyota Camry Automatic_vehicle_photo.png',
    kiaPickanto: '/img/vehicles/Kia-Picanto.png_Kia Picanto Automatic_vehicle_photo.png',
    hyundaiTucson: '/img/vehicles/HYUNDAI-TUCSON-2023.png_Hyundai Tucson Automatic_vehicle_photo.png',
    mercedesC200: '/img/vehicles/Mercedes-C---200-2021[1].png_Mercedes C200 Automatic_vehicle_photo.png',
    gmcYukon: '/img/vehicles/GMC-Yukon-2024.png_GMC Yukon 2024 Automatic_vehicle_photo.png',
  },
  payment:{
    visa: '/img/payment/VISA-logo.png',
    mastercard: '/img/payment/Mastercard-logo.svg',
    knet: '/img/payment/knet-logo.png',
  },
};
